### ISSUE TITLE
I would like to hear the sounds from the street when I approach the window in a room 

### ISSUE THREAD

**Issue by Liinagit** [maciej-szlosarczyk/giraffe-experience#10]

**Comment by ligaletina** [comment]
Closed with commit #42 & merged with master

**Comment by Liinagit** [comment]
The sound doesn't work yet

**Comment by ligaletina** [comment]
Posponed due to technology limitations. Should we still add the icon in prototype, to keep the ide?

**Comment by Liinagit** [comment]
The icon is added, but the spund can be added in future development
