### ISSUE TITLE
Create a floor plan overlay in 360 tour

### ISSUE THREAD

**Issue by ligaletina** [maciej-szlosarczyk/giraffe-experience#30]
According to paper prototype

**Comment by ligaletina** [comment]
I dont have any plan of given flat, can we come up with any or it should be a realistic and I should draw one?

**Comment by Liinagit** [comment]
I don't think there is a need for very realistic plan

**Comment by ligaletina** [comment]
postponed due to technology limitations and would make the interface quite puzzled
