### ISSUE TITLE
Create the user interface prototype

### ISSUE THREAD

**Issue by Liinagit** [maciej-szlosarczyk/giraffe-experience#43]

**Comment by Liinagit** [comment]
The interface of the apartment view is created. In apartment folder home.html

**Comment by Liinagit** [comment]
There isn't a link yet to filtering prototype or 360 tour, but can create them later.

**Comment by ligaletina** [comment]
- provide the links from filtering to apartment view (images, titles) as soon as it's uploaded

**Comment by ligaletina** [comment]
completed by #33 and #60 and the Giraffee blog post
